name: Deploy to Server

on:
  push:
    branches: [ "main" ]   # деплой только при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/ai-book
            git pull
            source ai-book-bot/venv/bin/activate && pip install -r ai-book-bot/requirements.txt
            systemctl restart aibook-bot
            source ai-book-backend/venv/bin/activate && pip install -r ai-book-backend/requirements.txt
            systemctl restart aibook-backend
